name: Java CI with Maven
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Checkout Yangkit Repo
      uses: actions/checkout@v4
      with:
        repository: network-analytics/yangkit
        ref: feature/yangkit-complete-validation
        path: yangkit
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build and Install Yangkit (Skipping tests)
      run: mvn -B install --file yangkit/pom.xml -DskipTests
    - name: Build with Maven
      run: mvn -B package --file pom.xml
